### ISSUE TITLE
Dynamo DB 스키마 정의

### ISSUE THREAD

**Issue by BaekGeunYoung** [BaekGeunYoung/deliSHAs_backend#3]
Dynamo DB 스키마 정의

1. restaurant
- id
- name
- latitude
- longitude

2. menu
- id
- name
- price
- time (breakfast, lunch, dinner)
- restaurant_id

일단 필드는 요정도 ? ?

**Comment by SeoSeongHo** [comment]
RDB, Cache 처리 방식으로 결정
