### ISSUE TITLE
크롤러 구현

### ISSUE THREAD

**Issue by BaekGeunYoung** [BaekGeunYoung/deliSHAs_backend#9]
AWS lambda + cloudWatch 조합으로 serverless 환경에서 실행할 수 있는 cron job 정의

서울대학교 웹 페이지에서 크롤링 -> 정보 가공 후 RDS에 값 업데이트

**Comment by SeoSeongHo** [comment]
cloudwatch, lambda 조합으로 하면, lambda 몇 번 당 가격이 얼마정도 나오나요?

**Comment by BaekGeunYoung** [comment]
API 요청은 월 백만건까지 무료기 때문에 문제가 없을 것 같고, 로그도 월 5GB까지 무료라 지금 예상으론 프리티어 한도 내에서 가능할 것 같군요

**Comment by SeoSeongHo** [comment]
Rds 트래픽만 계산하면 되겠군요
근데 며칠에 한 번씩 도는거라 적은 비용을 예상해도 되겠네요
